### ISSUE TITLE
Code incomplete?

### ISSUE THREAD

**Issue by pcav** [ClayJarCom/HeightmapExport#10]
Please make sure the code in the repo is complete.
Thanks.

**Comment by ClayJarCom** [comment]
Code was complete (in two branches, one for QGIS 2 and one for QGIS 3), but it has since been completely reworked.  As of version 0.5.0, the same code (and the same packaged plugin) supports both QGIS 2 and QGIS 3.  Also, a new PathTracer dialog has been added which allows for engraving paths from SVGs onto model created from heightmaps.
